!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        10zJrQ08-Branches:
          path: dataset/10zJrQ08-Branches
          prefix: ncino
          standardFeature: false
          versions:
            Fall 2019 V2:
              modifiedDate: '2022-08-09 12:30:14'
        10zJrQ08-nFORCE_Languages:
          path: dataset/10zJrQ08-nFORCE_Languages
          prefix: ncino
          standardFeature: false
          versions:
            Fall 2019:
              modifiedDate: '2022-08-09 12:30:14'
